// apps/react/src/App.tsx
import './App.css'
import '@shoelace-style/shoelace/dist/themes/light.css'
import '@shoelace-style/shoelace/dist/themes/dark.css'

import { SlButton, SlCard, SlIcon, SlInput } from '@shoelace-style/shoelace/dist/react'
import { getConcreteNumberTrivia, getRandomNumberTrivia } from './api/numberTrivia'

import { INumberTrivia } from 'business/numberTrivia/domain/entities/INumberTrivia'
import logo from './assets/react.svg'
import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path'
import { useState } from 'react'

setBasePath('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.83/dist/')

function App() {
  const [number, setNumber] = useState('')
  const [trivia, setTrivia] = useState<INumberTrivia>()

  const handleInputChange = (evt: any) => setNumber(evt.target.value)

  const searchTriviaFromInput = async () => {
    const numberTrivia = await getConcreteNumberTrivia(number)
    setTrivia(numberTrivia)
  }

  const searchRandomTrivia = async () => {
    const numberTrivia = await getRandomNumberTrivia()
    setTrivia(numberTrivia)
  }

  return (
    <div className="w-screen h-screen bg-base color-base flex justify-center items-center gap-4">
      <div className="fixed top-0 left-0 w-full flex items-center p-4">
        <div className="text-xl font-bold">Clean Architecture React Example</div>
        <div className="flex-grow"></div>
        <a href="https://github.com/roboncode/clean-architecture" target="_blank" rel="noreferrer">
          <SlIcon name="github" className="text-2xl" />
        </a>
      </div>
      <SlCard className="shadow-lg w-full max-w-md">
        <div slot="header" className="flex items-center gap-2 text-xl font-bold">
          <img src={logo} className="w-6" />
          <div>Number Trivia</div>
        </div>
        <div className="grid gap-4">
          {trivia && (
            <div className="text-center space-y-2">
              <div className="text-4xl font-bold">{trivia.number}</div>
              <div className="text-lg">{trivia.text}</div>
            </div>
          )}
          <SlInput
            type="number"
            placeholder="Input a number"
            size="large"
            className="w-full"
            value={number}
            onSlInput={handleInputChange}
          >
            <SlIcon name="search" slot="prefix"></SlIcon>
          </SlInput>
          <div className="flex gap-4">
            <SlButton variant="success" className="w-full" onClick={searchTriviaFromInput}>
              Search
            </SlButton>
            <SlButton className="w-full" onClick={searchRandomTrivia}>
              Get Random Trivia
            </SlButton>
          </div>
        </div>
      </SlCard>
    </div>
  )
}

export default App

// apps/vue/src/App.vue
<script setup lang="ts">
import '@shoelace-style/shoelace/dist/components/card/card.js'
import '@shoelace-style/shoelace/dist/components/input/input.js'
import '@shoelace-style/shoelace/dist/components/button/button.js'
import { ref } from 'vue'
import { getConcreteNumberTrivia, getRandomNumberTrivia } from './api/numberTrivia'
import { INumberTrivia } from 'business/numberTrivia/domain/entities/INumberTrivia'


const number = ref('')
const trivia = ref<INumberTrivia>()

const handleInputChange = (evt: any) => number.value = evt.target.value

const searchTriviaFromInput = async () => {
  const numberTrivia = await getConcreteNumberTrivia(number.value)
  trivia.value = numberTrivia
}

const searchRandomTrivia = async () => {
  const numberTrivia = await getRandomNumberTrivia()
  trivia.value = numberTrivia
}
</script>

<template>
  <div className="w-screen h-screen bg-base color-base flex justify-center items-center gap-4">
    <div class="fixed top-0 left-0 w-full flex items-center p-4">
      <div class="text-xl font-bold">Clean Architecture Vue Example</div>
      <div class="flex-grow"></div>
      <a href="https://github.com/roboncode/clean-architecture" target="_blank"><sl-icon name="github" class="text-2xl"></sl-icon></a>
    </div>
    <sl-card class="shadow-lg w-full max-w-md">
      <div slot="header" class="flex items-center gap-2 text-xl font-bold">
        <img src="./assets/vue.svg" class="w-6" alt="Vue logo" />
        <div>Number Trivia</div>
      </div>
      <div class="grid gap-4">
        <div v-if="trivia" class="text-center space-y-2">
          <div class="text-4xl font-bold">{{trivia.number}}</div>
          <div class="text-lg">{{trivia.text}}</div>
        </div>
        <sl-input type="number" placeholder="Input a number" size="large" class="w-full" @input="handleInputChange">
          <sl-icon name="search" slot="prefix"></sl-icon>
        </sl-input>
        <div class="flex gap-4">
          <sl-button variant="success" class="w-full" @click="searchTriviaFromInput"> Search </sl-button>
          <sl-button class="w-full" @click="searchRandomTrivia"> Get Random Trivia </sl-button>
        </div>
      </div>
    </sl-card>
  </div>
</template>
